Data types overview task
andreamamchur/js-basic pull request #4
Opened 2019-10-21 20:39 UTC by andreamamchur

2019-10-23 11:29 UTC, Mike-Savin requested changes

2019-10-23 11:29 UTC, Mike-Savin commented on Exercises/data-types-overview/data-types-overview.js
> +}
Try to rewrite the code to fill empty object, not prefilled with zero values.

2019-10-23 11:29 UTC, Mike-Savin commented on Exercises/data-types-overview/data-types-overview.js
> +const booleanVariable2 = Boolean(false);
When you use `Number/String/Boolean` without `new` keyword before it is not a constructor but just a function. You can read some facts about the difference here:
https://stackoverflow.com/a/4719342
In this task constructors should be used, not functions.

2019-10-25 19:43 UTC, lizarusi requested changes

2019-10-25 19:43 UTC, lizarusi commented on Exercises/data-types-overview/data-types-overview.js
> +const object = {
you can create object with constructor as well

2019-10-25 19:43 UTC, lizarusi commented on Exercises/data-types-overview/data-types-overview.js
> +objectWithReferences.number = 123.123;
👍

2019-10-25 19:43 UTC, lizarusi commented on Exercises/data-types-overview/data-types-overview.js
> +    if (typesCount[typeof array[i]] === undefined) {
great! now you should know logical operators and can simplify it :)

2019-11-01 12:13 UTC, Mike-Savin approved these changes

2019-11-01 16:02 UTC, merged