HW5 if-else-switch task
andreamamchur/js-basic pull request #9
Opened 2019-10-24 16:43 UTC by andreamamchur

2019-10-25 11:43 UTC, lizarusi requested changes
awesome work!

2019-10-25 11:43 UTC, lizarusi commented on Exercises/if-else-switch/if-else-switch.js
> +  for (const char of password) {
better to iterate through `specialCharacters` array

2019-10-25 11:43 UTC, lizarusi commented on Exercises/if-else-switch/if-else-switch.js
> +  if (password === password.toLowerCase()) {
👍

2019-10-25 11:43 UTC, lizarusi commented on Exercises/if-else-switch/if-else-switch.js
> +    switch (char) {
the idea here, is to get value of key i.e. `length`, `empty`... and use it in switch cases.

2019-11-01 09:57 UTC, Mike-Savin approved these changes
👍

2019-11-01 09:57 UTC, Mike-Savin commented on Exercises/if-else-switch/if-else-switch.js
> +  }
Looks good. You can also try to use `array.some` method here if you want:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/some

2019-11-01 16:02 UTC, merged